"""Centralized i18n strings for all 20 supported languages.

Single source of truth for user-facing strings across the bot.
All user-facing text that is NOT generated by the LLM must go through
this module or reference its dictionaries.

Language codes (20): de, en, fr, es, it, pt, nl, pl, sv, tr,
                     ru, uk, zh, ja, ko, ar, hi, id, th, vi

Design:
    - Every dict MUST have an "en" key as ultimate fallback.
    - get_text() looks up lang -> falls back to "en".
    - All keys are validated at import time (see _validate_dicts).
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Master language list (synced with domain.onboarding.WIZARD_LANGUAGES)
# ---------------------------------------------------------------------------

ALL_LANGUAGES: list[str] = [
    "de",
    "en",
    "fr",
    "es",
    "it",
    "pt",
    "nl",
    "pl",
    "sv",
    "tr",
    "ru",
    "uk",
    "zh",
    "ja",
    "ko",
    "ar",
    "hi",
    "id",
    "th",
    "vi",
]

ALL_LANGUAGE_SET: frozenset[str] = frozenset(ALL_LANGUAGES)

# ---------------------------------------------------------------------------
# /reset confirmation
# ---------------------------------------------------------------------------

RESET_TEXTS: dict[str, str] = {
    "de": "Konversation zurückgesetzt. Wir starten frisch!",
    "en": "Conversation reset. Let's start fresh!",
    "fr": "Conversation réinitialisée. On repart à zéro !",
    "es": "Conversación reiniciada. ¡Empecemos de nuevo!",
    "it": "Conversazione reimpostata. Ricominciamo da capo!",
    "pt": "Conversa reiniciada. Vamos começar do zero!",
    "nl": "Gesprek gereset. We beginnen opnieuw!",
    "pl": "Konwersacja zresetowana. Zaczynamy od nowa!",
    "sv": "Konversation återställd. Vi börjar om!",
    "tr": "Sohbet sıfırlandı. Yeniden başlayalım!",
    "ru": "Разговор сброшен. Начнём сначала!",
    "uk": "Розмову скинуто. Починаємо заново!",
    "zh": "对话已重置。让我们重新开始！",
    "ja": "会話をリセットしました。最初からやり直しましょう！",
    "ko": "대화가 초기화되었습니다. 새로 시작합시다!",
    "ar": "تمت إعادة تعيين المحادثة. لنبدأ من جديد!",
    "hi": "बातचीत रीसेट की गई। नई शुरुआत करते हैं!",
    "id": "Percakapan direset. Mari mulai dari awal!",
    "th": "รีเซ็ตการสนทนาแล้ว เริ่มใหม่กันเลย!",
    "vi": "Cuộc trò chuyện đã được đặt lại. Hãy bắt đầu lại!",
}

# ---------------------------------------------------------------------------
# /remember confirmation
# ---------------------------------------------------------------------------

REMEMBER_SAVED_TEXTS: dict[str, str] = {
    "de": "Gespeichert. [{entry_id}]",
    "en": "Saved. [{entry_id}]",
    "fr": "Enregistré. [{entry_id}]",
    "es": "Guardado. [{entry_id}]",
    "it": "Salvato. [{entry_id}]",
    "pt": "Salvo. [{entry_id}]",
    "nl": "Opgeslagen. [{entry_id}]",
    "pl": "Zapisano. [{entry_id}]",
    "sv": "Sparat. [{entry_id}]",
    "tr": "Kaydedildi. [{entry_id}]",
    "ru": "Сохранено. [{entry_id}]",
    "uk": "Збережено. [{entry_id}]",
    "zh": "已保存。[{entry_id}]",
    "ja": "保存しました。[{entry_id}]",
    "ko": "저장되었습니다. [{entry_id}]",
    "ar": "تم الحفظ. [{entry_id}]",
    "hi": "सहेजा गया। [{entry_id}]",
    "id": "Tersimpan. [{entry_id}]",
    "th": "บันทึกแล้ว [{entry_id}]",
    "vi": "Đã lưu. [{entry_id}]",
}

REMEMBER_USAGE_TEXTS: dict[str, str] = {
    "de": (
        "Benutzung:\n"
        "/remember <Text>  speichert Text\n"
        "/remember <Label>  (als Antwort)  speichert Bot-Antwort mit Label"
    ),
    "en": (
        "Usage:\n"
        "/remember <text>  save text\n"
        "/remember <label>  (as reply)  save bot response with label"
    ),
    "fr": (
        "Utilisation :\n"
        "/remember <texte>  enregistrer du texte\n"
        "/remember <label>  (en réponse)  enregistrer la réponse du bot"
    ),
    "es": (
        "Uso:\n"
        "/remember <texto>  guardar texto\n"
        "/remember <etiqueta>  (como respuesta)  guardar respuesta del bot"
    ),
    "it": (
        "Utilizzo:\n"
        "/remember <testo>  salva testo\n"
        "/remember <etichetta>  (come risposta)  salva risposta del bot"
    ),
    "pt": (
        "Uso:\n"
        "/remember <texto>  salvar texto\n"
        "/remember <rótulo>  (como resposta)  salvar resposta do bot"
    ),
    "nl": (
        "Gebruik:\n"
        "/remember <tekst>  tekst opslaan\n"
        "/remember <label>  (als antwoord)  bot-antwoord opslaan"
    ),
    "pl": (
        "Użycie:\n"
        "/remember <tekst>  zapisz tekst\n"
        "/remember <etykieta>  (jako odpowiedź)  zapisz odpowiedź bota"
    ),
    "sv": (
        "Användning:\n"
        "/remember <text>  spara text\n"
        "/remember <etikett>  (som svar)  spara bot-svar"
    ),
    "tr": (
        "Kullanım:\n"
        "/remember <metin>  metin kaydet\n"
        "/remember <etiket>  (yanıt olarak)  bot yanıtını kaydet"
    ),
    "ru": (
        "Использование:\n"
        "/remember <текст>  сохранить текст\n"
        "/remember <метка>  (в ответ)  сохранить ответ бота"
    ),
    "uk": (
        "Використання:\n"
        "/remember <текст>  зберегти текст\n"
        "/remember <мітка>  (у відповідь)  зберегти відповідь бота"
    ),
    "zh": (
        "用法：\n"
        "/remember <文本>  保存文本\n"
        "/remember <标签>  （作为回复）保存机器人回复"
    ),
    "ja": (
        "使い方：\n"
        "/remember <テキスト>  テキストを保存\n"
        "/remember <ラベル>  （返信として）ボットの回答を保存"
    ),
    "ko": (
        "사용법:\n"
        "/remember <텍스트>  텍스트 저장\n"
        "/remember <라벨>  (답장으로)  봇 응답 저장"
    ),
    "ar": (
        "الاستخدام:\n/remember <نص>  حفظ نص\n/remember <تسمية>  (كرد)  حفظ رد البوت"
    ),
    "hi": (
        "उपयोग:\n"
        "/remember <टेक्स्ट>  टेक्स्ट सहेजें\n"
        "/remember <लेबल>  (उत्तर के रूप में)  बॉट उत्तर सहेजें"
    ),
    "id": (
        "Penggunaan:\n"
        "/remember <teks>  simpan teks\n"
        "/remember <label>  (sebagai balasan)  simpan balasan bot"
    ),
    "th": (
        "การใช้งาน:\n"
        "/remember <ข้อความ>  บันทึกข้อความ\n"
        "/remember <ป้ายกำกับ>  (เป็นการตอบกลับ)  บันทึกคำตอบบอท"
    ),
    "vi": (
        "Cách dùng:\n"
        "/remember <văn bản>  lưu văn bản\n"
        "/remember <nhãn>  (trả lời)  lưu phản hồi của bot"
    ),
}

# ---------------------------------------------------------------------------
# /forget confirmation
# ---------------------------------------------------------------------------

FORGET_SUCCESS_TEXTS: dict[str, str] = {
    "de": (
        "Vergessen: {entry_id}\n\n"
        "Hinweis: Wenn der Inhalt noch im aktuellen Gespräch ist, "
        "nutze /reset für einen vollen Neustart."
    ),
    "en": (
        "Forgotten: {entry_id}\n\n"
        "Note: If the content is in the current conversation, "
        "use /reset for a full restart."
    ),
    "fr": (
        "Oublié : {entry_id}\n\n"
        "Note : si le contenu est dans la conversation actuelle, "
        "utilise /reset pour un redémarrage complet."
    ),
    "es": (
        "Olvidado: {entry_id}\n\n"
        "Nota: si el contenido está en la conversación actual, "
        "usa /reset para reiniciar completamente."
    ),
    "it": (
        "Dimenticato: {entry_id}\n\n"
        "Nota: se il contenuto è nella conversazione attuale, "
        "usa /reset per un riavvio completo."
    ),
    "pt": (
        "Esquecido: {entry_id}\n\n"
        "Nota: se o conteúdo está na conversa atual, "
        "use /reset para reiniciar completamente."
    ),
    "nl": (
        "Vergeten: {entry_id}\n\n"
        "Opmerking: als de inhoud in het huidige gesprek staat, "
        "gebruik /reset voor een volledige herstart."
    ),
    "pl": (
        "Zapomniano: {entry_id}\n\n"
        "Uwaga: jeśli treść jest w bieżącej rozmowie, "
        "użyj /reset aby zacząć od nowa."
    ),
    "sv": (
        "Glömt: {entry_id}\n\n"
        "Obs: om innehållet finns i den aktuella konversationen, "
        "använd /reset för en fullständig omstart."
    ),
    "tr": (
        "Unutuldu: {entry_id}\n\n"
        "Not: İçerik mevcut sohbette ise, "
        "tam yeniden başlatma için /reset kullanın."
    ),
    "ru": (
        "Забыто: {entry_id}\n\n"
        "Примечание: если содержимое в текущем разговоре, "
        "используйте /reset для полного перезапуска."
    ),
    "uk": (
        "Забуто: {entry_id}\n\n"
        "Примітка: якщо вміст є в поточній розмові, "
        "використовуйте /reset для повного перезапуску."
    ),
    "zh": (
        "已遗忘：{entry_id}\n\n注意：如果内容在当前对话中，请使用 /reset 完全重新开始。"
    ),
    "ja": (
        "忘却しました：{entry_id}\n\n"
        "注意：内容が現在の会話にある場合は、"
        "/reset で完全にリスタートしてください。"
    ),
    "ko": (
        "잊었습니다: {entry_id}\n\n"
        "참고: 내용이 현재 대화에 있는 경우, "
        "/reset으로 완전히 다시 시작하세요."
    ),
    "ar": (
        "تم النسيان: {entry_id}\n\n"
        "ملاحظة: إذا كان المحتوى في المحادثة الحالية، "
        "استخدم /reset لإعادة تشغيل كاملة."
    ),
    "hi": (
        "भुला दिया: {entry_id}\n\n"
        "नोट: अगर सामग्री वर्तमान बातचीत में है, "
        "पूर्ण पुनरारंभ के लिए /reset का उपयोग करें।"
    ),
    "id": (
        "Dilupakan: {entry_id}\n\n"
        "Catatan: jika konten ada dalam percakapan saat ini, "
        "gunakan /reset untuk memulai ulang sepenuhnya."
    ),
    "th": (
        "ลืมแล้ว: {entry_id}\n\n"
        "หมายเหตุ: หากเนื้อหาอยู่ในการสนทนาปัจจุบัน "
        "ใช้ /reset เพื่อเริ่มต้นใหม่ทั้งหมด"
    ),
    "vi": (
        "Đã quên: {entry_id}\n\n"
        "Lưu ý: nếu nội dung nằm trong cuộc trò chuyện hiện tại, "
        "hãy dùng /reset để bắt đầu lại hoàn toàn."
    ),
}

FORGET_NOT_FOUND_TEXTS: dict[str, str] = {
    "de": "Eintrag '{entry_id}' nicht gefunden oder gehört dir nicht.",
    "en": "Entry '{entry_id}' not found or does not belong to you.",
    "fr": "Entrée '{entry_id}' introuvable ou ne vous appartient pas.",
    "es": "Entrada '{entry_id}' no encontrada o no te pertenece.",
    "it": "Voce '{entry_id}' non trovata o non ti appartiene.",
    "pt": "Entrada '{entry_id}' não encontrada ou não pertence a você.",
    "nl": "Item '{entry_id}' niet gevonden of behoort niet tot jou.",
    "pl": "Wpis '{entry_id}' nie znaleziony lub nie należy do ciebie.",
    "sv": "Post '{entry_id}' hittades inte eller tillhör inte dig.",
    "tr": "Giriş '{entry_id}' bulunamadı veya sana ait değil.",
    "ru": "Запись '{entry_id}' не найдена или не принадлежит вам.",
    "uk": "Запис '{entry_id}' не знайдено або не належить вам.",
    "zh": "条目 '{entry_id}' 未找到或不属于你。",
    "ja": "エントリー '{entry_id}' が見つからないか、あなたのものではありません。",
    "ko": "항목 '{entry_id}'을(를) 찾을 수 없거나 귀하의 것이 아닙니다.",
    "ar": "الإدخال '{entry_id}' غير موجود أو لا يخصك.",
    "hi": "प्रविष्टि '{entry_id}' नहीं मिली या आपकी नहीं है।",
    "id": "Entri '{entry_id}' tidak ditemukan atau bukan milik Anda.",
    "th": "รายการ '{entry_id}' ไม่พบหรือไม่ใช่ของคุณ",
    "vi": "Mục '{entry_id}' không tìm thấy hoặc không thuộc về bạn.",
}

FORGET_USAGE_TEXTS: dict[str, str] = {
    "de": "Benutzung: /forget <id>\n\nIDs findest du über /memory",
    "en": "Usage: /forget <entry_id>\n\nFind IDs via /memory",
    "fr": "Utilisation : /forget <id>\n\nTrouvez les IDs via /memory",
    "es": "Uso: /forget <id>\n\nEncuentra los IDs con /memory",
    "it": "Utilizzo: /forget <id>\n\nTrova gli ID con /memory",
    "pt": "Uso: /forget <id>\n\nEncontre os IDs com /memory",
    "nl": "Gebruik: /forget <id>\n\nVind IDs via /memory",
    "pl": "Użycie: /forget <id>\n\nZnajdź ID przez /memory",
    "sv": "Användning: /forget <id>\n\nHitta ID via /memory",
    "tr": "Kullanım: /forget <id>\n\nID'leri /memory ile bulun",
    "ru": "Использование: /forget <id>\n\nНайдите ID через /memory",
    "uk": "Використання: /forget <id>\n\nЗнайдіть ID через /memory",
    "zh": "用法：/forget <id>\n\n通过 /memory 查找 ID",
    "ja": "使い方：/forget <id>\n\nIDは /memory で確認できます",
    "ko": "사용법: /forget <id>\n\n/memory로 ID를 확인하세요",
    "ar": "الاستخدام: /forget <id>\n\nابحث عن المعرفات عبر /memory",
    "hi": "उपयोग: /forget <id>\n\nID /memory के माध्यम से खोजें",
    "id": "Penggunaan: /forget <id>\n\nTemukan ID melalui /memory",
    "th": "การใช้งาน: /forget <id>\n\nค้นหา ID ผ่าน /memory",
    "vi": "Cách dùng: /forget <id>\n\nTìm ID qua /memory",
}

# ---------------------------------------------------------------------------
# /memory display
# ---------------------------------------------------------------------------

MEMORY_EMPTY_TEXTS: dict[str, str] = {
    "de": "Noch keine Notizen gespeichert. Nutze /remember <Text> um etwas zu speichern.",
    "en": "No memories saved yet. Use /remember <text> to save something.",
    "fr": "Aucun souvenir enregistré. Utilise /remember <texte> pour sauvegarder.",
    "es": "Aún no hay recuerdos guardados. Usa /remember <texto> para guardar algo.",
    "it": "Nessun ricordo salvato. Usa /remember <testo> per salvare qualcosa.",
    "pt": "Nenhuma memória salva ainda. Use /remember <texto> para salvar algo.",
    "nl": "Nog geen herinneringen opgeslagen. Gebruik /remember <tekst> om iets op te slaan.",
    "pl": "Brak zapisanych wspomnień. Użyj /remember <tekst> aby coś zapisać.",
    "sv": "Inga minnen sparade ännu. Använd /remember <text> för att spara något.",
    "tr": "Henüz kaydedilmiş anı yok. Bir şey kaydetmek için /remember <metin> kullan.",
    "ru": "Записей пока нет. Используйте /remember <текст> чтобы сохранить что-то.",
    "uk": "Записів ще немає. Використовуйте /remember <текст> щоб зберегти щось.",
    "zh": "还没有保存的笔记。使用 /remember <文本> 来保存。",
    "ja": "まだメモがありません。/remember <テキスト> で保存できます。",
    "ko": "아직 저장된 메모가 없습니다. /remember <텍스트>로 저장하세요.",
    "ar": "لا توجد ذكريات محفوظة بعد. استخدم /remember <نص> لحفظ شيء.",
    "hi": "अभी तक कोई नोट सहेजा नहीं गया। /remember <टेक्स्ट> से कुछ सहेजें।",
    "id": "Belum ada memori tersimpan. Gunakan /remember <teks> untuk menyimpan.",
    "th": "ยังไม่มีบันทึก ใช้ /remember <ข้อความ> เพื่อบันทึก",
    "vi": "Chưa có ghi nhớ nào. Dùng /remember <văn bản> để lưu.",
}

MEMORY_HEADER_TEXTS: dict[str, str] = {
    "de": "Letzte {count} Notizen:\n",
    "en": "Last {count} memories:\n",
    "fr": "Derniers {count} souvenirs :\n",
    "es": "Últimos {count} recuerdos:\n",
    "it": "Ultimi {count} ricordi:\n",
    "pt": "Últimas {count} memórias:\n",
    "nl": "Laatste {count} herinneringen:\n",
    "pl": "Ostatnie {count} wspomnień:\n",
    "sv": "Senaste {count} minnen:\n",
    "tr": "Son {count} anı:\n",
    "ru": "Последние {count} записей:\n",
    "uk": "Останні {count} записів:\n",
    "zh": "最近 {count} 条笔记：\n",
    "ja": "最新 {count} 件のメモ：\n",
    "ko": "최근 {count}개 메모:\n",
    "ar": "آخر {count} ذكريات:\n",
    "hi": "अंतिम {count} नोट:\n",
    "id": "Terakhir {count} memori:\n",
    "th": "บันทึกล่าสุด {count} รายการ:\n",
    "vi": "Ghi nhớ gần đây ({count}):\n",
}

MEMORY_SEARCH_NO_RESULTS_TEXTS: dict[str, str] = {
    "de": "Keine Notizen passend zu '{query}' gefunden.",
    "en": "No memories matching '{query}' found.",
    "fr": "Aucun souvenir correspondant à '{query}' trouvé.",
    "es": "No se encontraron recuerdos para '{query}'.",
    "it": "Nessun ricordo trovato per '{query}'.",
    "pt": "Nenhuma memória encontrada para '{query}'.",
    "nl": "Geen herinneringen gevonden voor '{query}'.",
    "pl": "Nie znaleziono wspomnień dla '{query}'.",
    "sv": "Inga minnen hittades för '{query}'.",
    "tr": "'{query}' için eşleşen anı bulunamadı.",
    "ru": "Записей по запросу '{query}' не найдено.",
    "uk": "Записів за запитом '{query}' не знайдено.",
    "zh": "没有找到匹配 '{query}' 的笔记。",
    "ja": "'{query}' に一致するメモが見つかりません。",
    "ko": "'{query}'에 해당하는 메모를 찾을 수 없습니다.",
    "ar": "لم يتم العثور على ذكريات مطابقة لـ '{query}'.",
    "hi": "'{query}' से मेल खाते नोट नहीं मिले।",
    "id": "Tidak ada memori yang cocok dengan '{query}'.",
    "th": "ไม่พบบันทึกที่ตรงกับ '{query}'",
    "vi": "Không tìm thấy ghi nhớ cho '{query}'.",
}

MEMORY_SEARCH_HEADER_TEXTS: dict[str, str] = {
    "de": "Suchergebnisse für '{query}' ({count} Treffer):\n",
    "en": "Search results for '{query}' ({count} matches):\n",
    "fr": "Résultats pour '{query}' ({count} correspondances) :\n",
    "es": "Resultados para '{query}' ({count} coincidencias):\n",
    "it": "Risultati per '{query}' ({count} corrispondenze):\n",
    "pt": "Resultados para '{query}' ({count} correspondências):\n",
    "nl": "Zoekresultaten voor '{query}' ({count} resultaten):\n",
    "pl": "Wyniki dla '{query}' ({count} trafień):\n",
    "sv": "Sökresultat för '{query}' ({count} träffar):\n",
    "tr": "'{query}' için sonuçlar ({count} eşleşme):\n",
    "ru": "Результаты для '{query}' ({count} совпадений):\n",
    "uk": "Результати для '{query}' ({count} збігів):\n",
    "zh": "搜索结果 '{query}'（{count} 条匹配）：\n",
    "ja": "'{query}' の検索結果（{count} 件）：\n",
    "ko": "'{query}' 검색 결과 ({count}건):\n",
    "ar": "نتائج البحث عن '{query}' ({count} تطابقات):\n",
    "hi": "'{query}' के लिए परिणाम ({count} मिलान):\n",
    "id": "Hasil pencarian '{query}' ({count} kecocokan):\n",
    "th": "ผลการค้นหา '{query}' ({count} รายการ):\n",
    "vi": "Kết quả tìm kiếm '{query}' ({count} kết quả):\n",
}

# ---------------------------------------------------------------------------
# /save (bookmark) confirmation
# ---------------------------------------------------------------------------

BOOKMARK_SAVED_TEXTS: dict[str, str] = {
    "de": "Lesezeichen gespeichert",
    "en": "Bookmark saved",
    "fr": "Signet enregistré",
    "es": "Marcador guardado",
    "it": "Segnalibro salvato",
    "pt": "Favorito salvo",
    "nl": "Bladwijzer opgeslagen",
    "pl": "Zakładka zapisana",
    "sv": "Bokmärke sparat",
    "tr": "Yer imi kaydedildi",
    "ru": "Закладка сохранена",
    "uk": "Закладку збережено",
    "zh": "书签已保存",
    "ja": "ブックマーク保存済み",
    "ko": "북마크 저장됨",
    "ar": "تم حفظ الإشارة المرجعية",
    "hi": "बुकमार्क सहेजा गया",
    "id": "Bookmark tersimpan",
    "th": "บันทึกบุ๊กมาร์กแล้ว",
    "vi": "Đã lưu dấu trang",
}

BOOKMARK_REMOVED_TEXTS: dict[str, str] = {
    "de": "Lesezeichen entfernt",
    "en": "Bookmark removed",
    "fr": "Signet supprimé",
    "es": "Marcador eliminado",
    "it": "Segnalibro rimosso",
    "pt": "Favorito removido",
    "nl": "Bladwijzer verwijderd",
    "pl": "Zakładka usunięta",
    "sv": "Bokmärke borttaget",
    "tr": "Yer imi kaldırıldı",
    "ru": "Закладка удалена",
    "uk": "Закладку видалено",
    "zh": "书签已移除",
    "ja": "ブックマーク削除済み",
    "ko": "북마크 제거됨",
    "ar": "تمت إزالة الإشارة المرجعية",
    "hi": "बुकमार्क हटाया गया",
    "id": "Bookmark dihapus",
    "th": "ลบบุ๊กมาร์กแล้ว",
    "vi": "Đã xóa dấu trang",
}

BOOKMARK_SAVE_HINT_TEXTS: dict[str, str] = {
    "de": "Antworte auf eine Bot-Nachricht mit /save um sie als Lesezeichen zu speichern.",
    "en": "Reply to a bot message with /save to bookmark it.",
    "fr": "Réponds à un message du bot avec /save pour le mettre en signet.",
    "es": "Responde a un mensaje del bot con /save para guardarlo.",
    "it": "Rispondi a un messaggio del bot con /save per aggiungerlo ai segnalibri.",
    "pt": "Responda a uma mensagem do bot com /save para adicioná-la aos favoritos.",
    "nl": "Antwoord op een bot-bericht met /save om het als bladwijzer op te slaan.",
    "pl": "Odpowiedz na wiadomość bota poleceniem /save aby dodać zakładkę.",
    "sv": "Svara på ett bot-meddelande med /save för att bokmärka det.",
    "tr": "Bir bot mesajına /save ile yanıtlayarak yer imi olarak kaydedin.",
    "ru": "Ответьте на сообщение бота командой /save чтобы добавить закладку.",
    "uk": "Відповідайте на повідомлення бота командою /save щоб зберегти закладку.",
    "zh": "回复机器人消息并发送 /save 来添加书签。",
    "ja": "ボットのメッセージに /save と返信してブックマークできます。",
    "ko": "봇 메시지에 /save로 답장하여 북마크하세요.",
    "ar": "أجب على رسالة البوت بـ /save لحفظها كإشارة مرجعية.",
    "hi": "बॉट संदेश का /save से जवाब दें बुकमार्क करने के लिए।",
    "id": "Balas pesan bot dengan /save untuk menyimpannya.",
    "th": "ตอบกลับข้อความบอทด้วย /save เพื่อบุ๊กมาร์ก",
    "vi": "Trả lời tin nhắn bot bằng /save để đánh dấu trang.",
}

BOOKMARK_LIST_EMPTY_TEXTS: dict[str, str] = {
    "de": (
        "Du hast noch keine Lesezeichen. "
        "Antworte auf eine Bot-Nachricht mit /save um sie als Lesezeichen zu speichern."
    ),
    "en": (
        "You have no bookmarks yet. Reply to a bot message with /save to bookmark it."
    ),
    "fr": (
        "Tu n'as pas encore de signets. "
        "Réponds à un message du bot avec /save pour en ajouter."
    ),
    "es": (
        "No tienes marcadores todavía. "
        "Responde a un mensaje del bot con /save para guardar uno."
    ),
    "it": (
        "Non hai ancora segnalibri. "
        "Rispondi a un messaggio del bot con /save per aggiungerne uno."
    ),
    "pt": (
        "Você ainda não tem favoritos. "
        "Responda a uma mensagem do bot com /save para adicionar."
    ),
    "nl": (
        "Je hebt nog geen bladwijzers. "
        "Antwoord op een bot-bericht met /save om er een toe te voegen."
    ),
    "pl": ("Nie masz jeszcze zakładek. Odpowiedz na wiadomość bota poleceniem /save."),
    "sv": (
        "Du har inga bokmärken ännu. "
        "Svara på ett bot-meddelande med /save för att lägga till."
    ),
    "tr": ("Henüz yer imin yok. Bir bot mesajına /save ile yanıtla."),
    "ru": ("У вас пока нет закладок. Ответьте на сообщение бота командой /save."),
    "uk": (
        "У вас ще немає закладок. Відповідайте на повідомлення бота командою /save."
    ),
    "zh": "你还没有书签。回复机器人消息并发送 /save 来添加。",
    "ja": "まだブックマークがありません。ボットのメッセージに /save と返信して追加できます。",
    "ko": "아직 북마크가 없습니다. 봇 메시지에 /save로 답장하여 추가하세요.",
    "ar": "ليس لديك إشارات مرجعية بعد. أجب على رسالة البوت بـ /save لإضافة واحدة.",
    "hi": "आपके पास अभी कोई बुकमार्क नहीं है। बॉट संदेश का /save से जवाब दें।",
    "id": "Belum ada bookmark. Balas pesan bot dengan /save untuk menambahkan.",
    "th": "คุณยังไม่มีบุ๊กมาร์ก ตอบกลับข้อความบอทด้วย /save เพื่อเพิ่ม",
    "vi": "Bạn chưa có dấu trang nào. Trả lời tin nhắn bot bằng /save để thêm.",
}

BOOKMARK_DELETE_CONFIRM_TEXTS: dict[str, str] = {
    "de": "Lesezeichen{date_display} entfernt",
    "en": "Bookmark{date_display} removed",
    "fr": "Signet{date_display} supprimé",
    "es": "Marcador{date_display} eliminado",
    "it": "Segnalibro{date_display} rimosso",
    "pt": "Favorito{date_display} removido",
    "nl": "Bladwijzer{date_display} verwijderd",
    "pl": "Zakładka{date_display} usunięta",
    "sv": "Bokmärke{date_display} borttaget",
    "tr": "Yer imi{date_display} kaldırıldı",
    "ru": "Закладка{date_display} удалена",
    "uk": "Закладку{date_display} видалено",
    "zh": "书签{date_display}已移除",
    "ja": "ブックマーク{date_display}を削除しました",
    "ko": "북마크{date_display} 제거됨",
    "ar": "تمت إزالة الإشارة المرجعية{date_display}",
    "hi": "बुकमार्क{date_display} हटाया गया",
    "id": "Bookmark{date_display} dihapus",
    "th": "ลบบุ๊กมาร์ก{date_display}แล้ว",
    "vi": "Đã xóa dấu trang{date_display}",
}

# ---------------------------------------------------------------------------
# /lang confirmation
# ---------------------------------------------------------------------------

LANG_CHANGED_TEXTS: dict[str, str] = {
    "de": "Sprache gewechselt: {name} ({code})",
    "en": "Language changed: {name} ({code})",
    "fr": "Langue changée : {name} ({code})",
    "es": "Idioma cambiado: {name} ({code})",
    "it": "Lingua cambiata: {name} ({code})",
    "pt": "Idioma alterado: {name} ({code})",
    "nl": "Taal gewijzigd: {name} ({code})",
    "pl": "Język zmieniony: {name} ({code})",
    "sv": "Språk ändrat: {name} ({code})",
    "tr": "Dil değiştirildi: {name} ({code})",
    "ru": "Язык изменён: {name} ({code})",
    "uk": "Мову змінено: {name} ({code})",
    "zh": "语言已更改：{name} ({code})",
    "ja": "言語を変更しました：{name} ({code})",
    "ko": "언어 변경됨: {name} ({code})",
    "ar": "تم تغيير اللغة: {name} ({code})",
    "hi": "भाषा बदली गई: {name} ({code})",
    "id": "Bahasa diubah: {name} ({code})",
    "th": "เปลี่ยนภาษาแล้ว: {name} ({code})",
    "vi": "Đã đổi ngôn ngữ: {name} ({code})",
}

# ---------------------------------------------------------------------------
# Inline command warning (T19)
# ---------------------------------------------------------------------------

INLINE_COMMAND_WARNING_TEXTS: dict[str, str] = {
    "de": (
        "Hinweis: Befehle wie /setmodel oder /reset müssen in einer eigenen "
        "Nachricht gesendet werden, nicht zusammen mit Text."
    ),
    "en": (
        "Note: Commands like /setmodel or /reset must be sent as a separate "
        "message, not combined with text."
    ),
    "fr": (
        "Note : les commandes comme /setmodel ou /reset doivent être envoyées "
        "dans un message séparé, pas combinées avec du texte."
    ),
    "es": (
        "Nota: comandos como /setmodel o /reset deben enviarse en un mensaje "
        "separado, no combinados con texto."
    ),
    "it": (
        "Nota: comandi come /setmodel o /reset devono essere inviati in un "
        "messaggio separato, non combinati con testo."
    ),
    "pt": (
        "Nota: comandos como /setmodel ou /reset devem ser enviados em uma "
        "mensagem separada, não combinados com texto."
    ),
    "nl": (
        "Opmerking: commando's zoals /setmodel of /reset moeten in een apart "
        "bericht worden verzonden, niet gecombineerd met tekst."
    ),
    "pl": (
        "Uwaga: komendy takie jak /setmodel lub /reset muszą być wysłane "
        "w osobnej wiadomości, nie łączone z tekstem."
    ),
    "sv": (
        "Obs: kommandon som /setmodel eller /reset måste skickas i ett separat "
        "meddelande, inte kombinerat med text."
    ),
    "tr": (
        "Not: /setmodel veya /reset gibi komutlar ayrı bir mesaj olarak "
        "gönderilmelidir, metinle birleştirilmemelidir."
    ),
    "ru": (
        "Примечание: команды вроде /setmodel или /reset нужно отправлять "
        "отдельным сообщением, не комбинируя с текстом."
    ),
    "uk": (
        "Примітка: команди на кшталт /setmodel або /reset потрібно надсилати "
        "окремим повідомленням, не поєднуючи з текстом."
    ),
    "zh": "注意：/setmodel 或 /reset 等命令必须作为单独消息发送，不能与文本混合。",
    "ja": "注意：/setmodel や /reset などのコマンドは、テキストと一緒ではなく、別のメッセージとして送信してください。",
    "ko": "참고: /setmodel 또는 /reset과 같은 명령은 텍스트와 함께가 아닌 별도의 메시지로 보내야 합니다.",
    "ar": "ملاحظة: الأوامر مثل /setmodel أو /reset يجب إرسالها في رسالة منفصلة، وليس مع نص.",
    "hi": "नोट: /setmodel या /reset जैसे कमांड अलग संदेश में भेजने चाहिए, टेक्स्ट के साथ नहीं।",
    "id": "Catatan: perintah seperti /setmodel atau /reset harus dikirim sebagai pesan terpisah.",
    "th": "หมายเหตุ: คำสั่งเช่น /setmodel หรือ /reset ต้องส่งเป็นข้อความแยก ไม่รวมกับข้อความอื่น",
    "vi": "Lưu ý: các lệnh như /setmodel hoặc /reset phải được gửi riêng, không kết hợp với văn bản.",
}

# ---------------------------------------------------------------------------
# Status manager texts (20 languages)
# ---------------------------------------------------------------------------

STATUS_TEXTS: dict[str, dict[str, str]] = {
    "memory_loading": {
        "de": "\U0001f9e0 Lade Notizen…",
        "en": "\U0001f9e0 Loading memory…",
        "fr": "\U0001f9e0 Chargement des notes…",
        "es": "\U0001f9e0 Cargando notas…",
        "it": "\U0001f9e0 Caricamento note…",
        "pt": "\U0001f9e0 Carregando notas…",
        "nl": "\U0001f9e0 Notities laden…",
        "pl": "\U0001f9e0 Wczytywanie notatek…",
        "sv": "\U0001f9e0 Laddar anteckningar…",
        "tr": "\U0001f9e0 Notlar yükleniyor…",
        "ru": "\U0001f9e0 Загрузка заметок…",
        "uk": "\U0001f9e0 Завантаження нотаток…",
        "zh": "\U0001f9e0 加载笔记…",
        "ja": "\U0001f9e0 メモを読み込み中…",
        "ko": "\U0001f9e0 메모 불러오는 중…",
        "ar": "\U0001f9e0 تحميل الملاحظات…",
        "hi": "\U0001f9e0 नोट्स लोड हो रहे हैं…",
        "id": "\U0001f9e0 Memuat catatan…",
        "th": "\U0001f9e0 กำลังโหลดบันทึก…",
        "vi": "\U0001f9e0 Đang tải ghi nhớ…",
    },
    "memory_loaded": {
        "de": "\U0001f9e0 Lade Notizen… ({n} gefunden)",
        "en": "\U0001f9e0 Loading memory… ({n} entries)",
        "fr": "\U0001f9e0 Chargement des notes… ({n} trouvées)",
        "es": "\U0001f9e0 Cargando notas… ({n} encontradas)",
        "it": "\U0001f9e0 Caricamento note… ({n} trovate)",
        "pt": "\U0001f9e0 Carregando notas… ({n} encontradas)",
        "nl": "\U0001f9e0 Notities laden… ({n} gevonden)",
        "pl": "\U0001f9e0 Wczytywanie notatek… ({n} znalezionych)",
        "sv": "\U0001f9e0 Laddar anteckningar… ({n} hittade)",
        "tr": "\U0001f9e0 Notlar yükleniyor… ({n} bulundu)",
        "ru": "\U0001f9e0 Загрузка заметок… ({n} найдено)",
        "uk": "\U0001f9e0 Завантаження нотаток… ({n} знайдено)",
        "zh": "\U0001f9e0 加载笔记…（找到 {n} 条）",
        "ja": "\U0001f9e0 メモを読み込み中…（{n} 件）",
        "ko": "\U0001f9e0 메모 불러오는 중… ({n}건)",
        "ar": "\U0001f9e0 تحميل الملاحظات… ({n} وجدت)",
        "hi": "\U0001f9e0 नोट्स लोड हो रहे हैं… ({n} मिले)",
        "id": "\U0001f9e0 Memuat catatan… ({n} ditemukan)",
        "th": "\U0001f9e0 กำลังโหลดบันทึก… ({n} รายการ)",
        "vi": "\U0001f9e0 Đang tải ghi nhớ… ({n} mục)",
    },
    "thinking": {
        "de": "\U0001f4ad Denke nach…",
        "en": "\U0001f4ad Thinking…",
        "fr": "\U0001f4ad Réflexion en cours…",
        "es": "\U0001f4ad Pensando…",
        "it": "\U0001f4ad Sto pensando…",
        "pt": "\U0001f4ad Pensando…",
        "nl": "\U0001f4ad Nadenken…",
        "pl": "\U0001f4ad Myślę…",
        "sv": "\U0001f4ad Tänker…",
        "tr": "\U0001f4ad Düşünüyorum…",
        "ru": "\U0001f4ad Думаю…",
        "uk": "\U0001f4ad Думаю…",
        "zh": "\U0001f4ad 正在思考…",
        "ja": "\U0001f4ad 考え中…",
        "ko": "\U0001f4ad 생각 중…",
        "ar": "\U0001f4ad جارٍ التفكير…",
        "hi": "\U0001f4ad सोच रहा हूँ…",
        "id": "\U0001f4ad Sedang berpikir…",
        "th": "\U0001f4ad กำลังคิด…",
        "vi": "\U0001f4ad Đang suy nghĩ…",
    },
    "formatting": {
        "de": "✨ Formatiere…",
        "en": "✨ Formatting…",
        "fr": "✨ Mise en forme…",
        "es": "✨ Formateando…",
        "it": "✨ Formattazione…",
        "pt": "✨ Formatando…",
        "nl": "✨ Opmaken…",
        "pl": "✨ Formatowanie…",
        "sv": "✨ Formaterar…",
        "tr": "✨ Biçimlendiriliyor…",
        "ru": "✨ Форматирование…",
        "uk": "✨ Форматування…",
        "zh": "✨ 格式化中…",
        "ja": "✨ フォーマット中…",
        "ko": "✨ 서식 지정 중…",
        "ar": "✨ جارٍ التنسيق…",
        "hi": "✨ फॉर्मेट हो रहा है…",
        "id": "✨ Memformat…",
        "th": "✨ กำลังจัดรูปแบบ…",
        "vi": "✨ Đang định dạng…",
    },
}


# ---------------------------------------------------------------------------
# Helper function
# ---------------------------------------------------------------------------


def get_text(
    texts: dict[str, str],
    lang: str,
    **kwargs: Any,
) -> str:
    """Look up a localized string with fallback to English.

    Args:
        texts: Dict mapping language codes to strings.
        lang: User language code.
        **kwargs: Format parameters (e.g. entry_id, query, count).

    Returns:
        Formatted localized string.
    """
    template = texts.get(lang, texts.get("en", ""))
    if kwargs:
        try:
            return template.format(**kwargs)
        except (KeyError, IndexError):
            return template
    return template


def get_status_text(key: str, lang: str = "de", **kwargs: Any) -> str:
    """Return the localized status text.

    Args:
        key: Status key (e.g. "memory_loading", "thinking").
        lang: Language code.
        **kwargs: Format parameters (e.g. n=3 for memory count).

    Returns:
        Formatted status text.
    """
    texts = STATUS_TEXTS.get(key, {})
    template = texts.get(lang, texts.get("en", texts.get("de", key)))
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template


# ---------------------------------------------------------------------------
# Validation (runs at import time)
# ---------------------------------------------------------------------------


def _validate_dicts() -> None:
    """Ensure all i18n dicts have the "en" key.

    Runs at import time. Missing "en" key is a programming error.
    """
    _dicts = [
        ("RESET_TEXTS", RESET_TEXTS),
        ("REMEMBER_SAVED_TEXTS", REMEMBER_SAVED_TEXTS),
        ("REMEMBER_USAGE_TEXTS", REMEMBER_USAGE_TEXTS),
        ("FORGET_SUCCESS_TEXTS", FORGET_SUCCESS_TEXTS),
        ("FORGET_NOT_FOUND_TEXTS", FORGET_NOT_FOUND_TEXTS),
        ("FORGET_USAGE_TEXTS", FORGET_USAGE_TEXTS),
        ("MEMORY_EMPTY_TEXTS", MEMORY_EMPTY_TEXTS),
        ("MEMORY_HEADER_TEXTS", MEMORY_HEADER_TEXTS),
        ("MEMORY_SEARCH_NO_RESULTS_TEXTS", MEMORY_SEARCH_NO_RESULTS_TEXTS),
        ("MEMORY_SEARCH_HEADER_TEXTS", MEMORY_SEARCH_HEADER_TEXTS),
        ("BOOKMARK_SAVED_TEXTS", BOOKMARK_SAVED_TEXTS),
        ("BOOKMARK_REMOVED_TEXTS", BOOKMARK_REMOVED_TEXTS),
        ("BOOKMARK_SAVE_HINT_TEXTS", BOOKMARK_SAVE_HINT_TEXTS),
        ("BOOKMARK_LIST_EMPTY_TEXTS", BOOKMARK_LIST_EMPTY_TEXTS),
        ("BOOKMARK_DELETE_CONFIRM_TEXTS", BOOKMARK_DELETE_CONFIRM_TEXTS),
        ("LANG_CHANGED_TEXTS", LANG_CHANGED_TEXTS),
        ("INLINE_COMMAND_WARNING_TEXTS", INLINE_COMMAND_WARNING_TEXTS),
    ]
    for name, d in _dicts:
        assert "en" in d, f"i18n dict {name} is missing the 'en' key"


_validate_dicts()
