"""Built-in rule sets for Text Guard.

Each language has a curated word list derived from common LLM ASCII
diacritic errors. German rules are the most extensive (based on the
existing check_no_fake_umlauts.py word stems).

This module is pure Python: no YAML, no file I/O.
External YAML rule files can be loaded by the application layer
and merged into these built-in sets.
"""

from __future__ import annotations

from domain.text_guard.models import RuleSet, WordPair

# ---------------------------------------------------------------------------
# German (de): most extensive rule set
# Based on check_no_fake_umlauts.py stems + common LLM errors
# ---------------------------------------------------------------------------

_DE_WORD_PAIRS: tuple[WordPair, ...] = (
    # ae -> ae (alphabetical by ascii_form)
    WordPair("aehnlich", "ähnlich"),
    WordPair("aehnliche", "ähnliche"),
    WordPair("aehnliches", "ähnliches"),
    WordPair("aehnlichen", "ähnlichen"),
    WordPair("aehnlicher", "ähnlicher"),
    WordPair("aehnlichkeit", "Ähnlichkeit"),
    WordPair("aendern", "ändern"),
    WordPair("aendere", "ändere"),
    WordPair("aenderst", "änderst"),
    WordPair("aendert", "ändert"),
    WordPair("aenderung", "Änderung"),
    WordPair("aenderungen", "Änderungen"),
    WordPair("aerger", "Ärger"),
    WordPair("aergerlich", "ärgerlich"),
    WordPair("aerztin", "Ärztin"),
    WordPair("aerzte", "Ärzte"),
    WordPair("eigenstaendig", "eigenständig"),
    WordPair("eigenstaendige", "eigenständige"),
    WordPair("eigenstaendiges", "eigenständiges"),
    WordPair("enthaelt", "enthält"),
    WordPair("erklaere", "erkläre"),
    WordPair("erklaeren", "erklären"),
    WordPair("erklaert", "erklärt"),
    WordPair("erklaerung", "Erklärung"),
    WordPair("erklaerungen", "Erklärungen"),
    WordPair("gaebe", "gäbe"),
    WordPair("gaengig", "gängig"),
    WordPair("gaengige", "gängige"),
    WordPair("gefaehrlich", "gefährlich"),
    WordPair("gefaehrliche", "gefährliche"),
    WordPair("gefaehrliches", "gefährliches"),
    WordPair("gespraech", "Gespräch"),
    WordPair("gespraeche", "Gespräche"),
    WordPair("haelt", "hält"),
    WordPair("haette", "hätte"),
    WordPair("haetten", "hätten"),
    WordPair("haeufig", "häufig"),
    WordPair("haeufige", "häufige"),
    WordPair("haeufiger", "häufiger"),
    WordPair("haeufigkeit", "Häufigkeit"),
    WordPair("laecheln", "lächeln"),
    WordPair("laechelt", "lächelt"),
    WordPair("laedt", "lädt"),
    WordPair("laengst", "längst"),
    WordPair("laenger", "länger"),
    WordPair("laengere", "längere"),
    WordPair("laengerem", "längerem"),
    WordPair("laengeren", "längeren"),
    WordPair("laesst", "lässt"),
    WordPair("laestig", "lästig"),
    WordPair("laeuft", "läuft"),
    WordPair("maechtig", "mächtig"),
    WordPair("maechtige", "mächtige"),
    WordPair("maedchen", "Mädchen"),
    WordPair("maennlich", "männlich"),
    WordPair("maennliche", "männliche"),
    WordPair("naechste", "nächste"),
    WordPair("naechsten", "nächsten"),
    WordPair("naechster", "nächster"),
    WordPair("naechstes", "nächstes"),
    WordPair("naemlich", "nämlich"),
    WordPair("praeferenz", "Präferenz"),
    WordPair("praeferenzen", "Präferenzen"),
    WordPair("praefix", "Präfix"),
    WordPair("praezise", "präzise"),
    WordPair("praeziser", "präziser"),
    WordPair("praezision", "Präzision"),
    WordPair("prioritaet", "Priorität"),
    WordPair("prioritaeten", "Prioritäten"),
    WordPair("saetze", "Sätze"),
    WordPair("saetzen", "Sätzen"),
    WordPair("schaerfer", "schärfer"),
    WordPair("schaerfere", "schärfere"),
    WordPair("schwaeche", "Schwäche"),
    WordPair("schwaechen", "Schwächen"),
    WordPair("spaeter", "später"),
    WordPair("spaetere", "spätere"),
    WordPair("spaetestens", "spätestens"),
    WordPair("staerke", "Stärke"),
    WordPair("staerken", "Stärken"),
    WordPair("staerker", "stärker"),
    WordPair("staerkere", "stärkere"),
    WordPair("taetigkeit", "Tätigkeit"),
    WordPair("taetigkeiten", "Tätigkeiten"),
    WordPair("taeglich", "täglich"),
    WordPair("taegliche", "tägliche"),
    WordPair("vollstaendig", "vollständig"),
    WordPair("vollstaendige", "vollständige"),
    WordPair("vollstaendiges", "vollständiges"),
    WordPair("vollstaendigkeit", "Vollständigkeit"),
    WordPair("vorschlaege", "Vorschläge"),
    WordPair("vorschlaegen", "Vorschlägen"),
    WordPair("waehlen", "wählen"),
    WordPair("waehle", "wähle"),
    WordPair("waehlt", "wählt"),
    WordPair("waehrend", "während"),
    WordPair("waehrung", "Währung"),
    WordPair("waehrungen", "Währungen"),
    WordPair("waere", "wäre"),
    WordPair("waeren", "wären"),
    WordPair("zusaetzlich", "zusätzlich"),
    WordPair("zusaetzliche", "zusätzliche"),
    WordPair("zusaetzliches", "zusätzliches"),
    # oe -> oe (alphabetical by ascii_form)
    WordPair("boese", "böse"),
    WordPair("boeser", "böser"),
    WordPair("boeses", "böses"),
    WordPair("franzoesisch", "französisch"),
    WordPair("franzoesische", "französische"),
    WordPair("gehoert", "gehört"),
    WordPair("gehoeren", "gehören"),
    WordPair("geloescht", "gelöscht"),
    WordPair("geloeschte", "gelöschte"),
    WordPair("gewoehnlich", "gewöhnlich"),
    WordPair("gewoehnliche", "gewöhnliche"),
    WordPair("groesse", "Größe"),
    WordPair("groessen", "Größen"),
    WordPair("groesser", "größer"),
    WordPair("groessere", "größere"),
    WordPair("groesste", "größte"),
    WordPair("groessten", "größten"),
    WordPair("groesstenteils", "größtenteils"),
    WordPair("hoeflich", "höflich"),
    WordPair("hoefliche", "höfliche"),
    WordPair("hoeflichkeit", "Höflichkeit"),
    WordPair("hoeren", "hören"),
    WordPair("hoere", "höre"),
    WordPair("hoerst", "hörst"),
    WordPair("hoert", "hört"),
    WordPair("koennen", "können"),
    WordPair("koennte", "könnte"),
    WordPair("koennten", "könnten"),
    WordPair("koenntest", "könntest"),
    WordPair("koerper", "Körper"),
    WordPair("koerperlich", "körperlich"),
    WordPair("loeschen", "löschen"),
    WordPair("loesche", "lösche"),
    WordPair("loeschst", "löschst"),
    WordPair("loescht", "löscht"),
    WordPair("loesung", "Lösung"),
    WordPair("loesungen", "Lösungen"),
    WordPair("moechte", "möchte"),
    WordPair("moechten", "möchten"),
    WordPair("moechtest", "möchtest"),
    WordPair("moeglich", "möglich"),
    WordPair("moegliche", "mögliche"),
    WordPair("moegliches", "mögliches"),
    WordPair("moeglichen", "möglichen"),
    WordPair("moeglicher", "möglicher"),
    WordPair("moeglichkeit", "Möglichkeit"),
    WordPair("moeglichkeiten", "Möglichkeiten"),
    WordPair("moeglichst", "möglichst"),
    WordPair("noetig", "nötig"),
    WordPair("noetige", "nötige"),
    WordPair("noetigen", "nötigen"),
    WordPair("oeffentlich", "öffentlich"),
    WordPair("oeffentliche", "öffentliche"),
    WordPair("oeffentliches", "öffentliches"),
    WordPair("oeffentlichen", "öffentlichen"),
    WordPair("oeffentlichkeit", "Öffentlichkeit"),
    WordPair("oeffnen", "öffnen"),
    WordPair("oeffne", "öffne"),
    WordPair("oeffnet", "öffnet"),
    WordPair("oeffnung", "Öffnung"),
    WordPair("persoenlich", "persönlich"),
    WordPair("persoenliche", "persönliche"),
    WordPair("persoenliches", "persönliches"),
    WordPair("persoenlichen", "persönlichen"),
    WordPair("stoerung", "Störung"),
    WordPair("stoerungen", "Störungen"),
    WordPair("voellig", "völlig"),
    WordPair("woertlich", "wörtlich"),
    WordPair("woerter", "Wörter"),
    WordPair("woerterbuch", "Wörterbuch"),
    WordPair("zuhoerer", "Zuhörer"),
    # ue -> ue (alphabetical by ascii_form)
    WordPair("ausfuehren", "ausführen"),
    WordPair("ausfuehrlich", "ausführlich"),
    WordPair("ausfuehrliche", "ausführliche"),
    WordPair("ausfuehrung", "Ausführung"),
    WordPair("begruenden", "begründen"),
    WordPair("begruendung", "Begründung"),
    WordPair("beruecksichtigen", "berücksichtigen"),
    WordPair("beruecksichtigt", "berücksichtigt"),
    WordPair("beruecksichtigung", "Berücksichtigung"),
    WordPair("durchfuehren", "durchführen"),
    WordPair("durchfuehrung", "Durchführung"),
    WordPair("duerften", "dürften"),
    WordPair("duerfte", "dürfte"),
    WordPair("einfuehren", "einführen"),
    WordPair("einfuehrung", "Einführung"),
    WordPair("eingefuehrt", "eingeführt"),
    WordPair("fuer", "für"),
    WordPair("fuehlen", "fühlen"),
    WordPair("fuehle", "fühle"),
    WordPair("fuehlt", "fühlt"),
    WordPair("fuehren", "führen"),
    WordPair("fuehre", "führe"),
    WordPair("fuehrt", "führt"),
    WordPair("fuehrung", "Führung"),
    WordPair("fuenf", "fünf"),
    WordPair("geprueft", "geprüft"),
    WordPair("gewuenscht", "gewünscht"),
    WordPair("gewuenschte", "gewünschte"),
    WordPair("glueck", "Glück"),
    WordPair("gluecklich", "glücklich"),
    WordPair("glueckliche", "glückliche"),
    WordPair("gruende", "Gründe"),
    WordPair("gruenden", "Gründen"),
    WordPair("gruendlich", "gründlich"),
    WordPair("gruendliche", "gründliche"),
    WordPair("gueltig", "gültig"),
    WordPair("gueltige", "gültige"),
    WordPair("gueltigkeit", "Gültigkeit"),
    WordPair("guenstig", "günstig"),
    WordPair("guenstige", "günstige"),
    WordPair("guenstiger", "günstiger"),
    WordPair("kuemmern", "kümmern"),
    WordPair("kuemmere", "kümmere"),
    WordPair("kuemmert", "kümmert"),
    WordPair("kuendigen", "kündigen"),
    WordPair("kuendigung", "Kündigung"),
    WordPair("kuenftig", "künftig"),
    WordPair("kuenftige", "künftige"),
    WordPair("kuenstlich", "künstlich"),
    WordPair("kuenstliche", "künstliche"),
    WordPair("muede", "müde"),
    WordPair("muessen", "müssen"),
    WordPair("muesste", "müsste"),
    WordPair("muessten", "müssten"),
    WordPair("natuerlich", "natürlich"),
    WordPair("natuerliche", "natürliche"),
    WordPair("natuerliches", "natürliches"),
    WordPair("nuetzlich", "nützlich"),
    WordPair("nuetzliche", "nützliche"),
    WordPair("nuetzliches", "nützliches"),
    WordPair("pruefen", "prüfen"),
    WordPair("pruefe", "prüfe"),
    WordPair("prueft", "prüft"),
    WordPair("pruefung", "Prüfung"),
    WordPair("pruefungen", "Prüfungen"),
    WordPair("schluessel", "Schlüssel"),
    WordPair("selbstverstaendlich", "selbstverständlich"),
    WordPair("stueck", "Stück"),
    WordPair("stuecke", "Stücke"),
    WordPair("ueber", "über"),
    WordPair("ueberall", "überall"),
    WordPair("ueberblick", "Überblick"),
    WordPair("uebereinstimmung", "Übereinstimmung"),
    WordPair("uebergeben", "übergeben"),
    WordPair("uebergibt", "übergibt"),
    WordPair("ueberhaupt", "überhaupt"),
    WordPair("ueberlegen", "überlegen"),
    WordPair("ueberlegung", "Überlegung"),
    WordPair("ueberlegungen", "Überlegungen"),
    WordPair("uebernehmen", "übernehmen"),
    WordPair("uebernimmt", "übernimmt"),
    WordPair("ueberpruefen", "überprüfen"),
    WordPair("ueberprueft", "überprüft"),
    WordPair("ueberpruefung", "Überprüfung"),
    WordPair("ueberraschung", "Überraschung"),
    WordPair("ueberschrift", "Überschrift"),
    WordPair("uebersetzen", "übersetzen"),
    WordPair("uebersetzung", "Übersetzung"),
    WordPair("uebersicht", "Übersicht"),
    WordPair("uebrigens", "übrigens"),
    WordPair("ungueltig", "ungültig"),
    WordPair("ungueltige", "ungültige"),
    WordPair("unterstuetzen", "unterstützen"),
    WordPair("unterstuetzt", "unterstützt"),
    WordPair("unterstuetzung", "Unterstützung"),
    WordPair("verfuegbar", "verfügbar"),
    WordPair("verfuegbare", "verfügbare"),
    WordPair("verfuegbares", "verfügbares"),
    WordPair("verfuegbarkeit", "Verfügbarkeit"),
    WordPair("verfuegen", "verfügen"),
    WordPair("verfuegung", "Verfügung"),
    WordPair("verguenstigung", "Vergünstigung"),
    WordPair("wuerde", "würde"),
    WordPair("wuerden", "würden"),
    WordPair("wuerdest", "würdest"),
    WordPair("wuenschen", "wünschen"),
    WordPair("wuensche", "wünsche"),
    WordPair("wuenscht", "wünscht"),
    WordPair("zukunft", "Zukunft"),
    WordPair("zurueck", "zurück"),
    WordPair("zurueckgeben", "zurückgeben"),
    WordPair("zurueckkehren", "zurückkehren"),
    WordPair("zusammenfuegen", "zusammenfügen"),
    # ss -> ss (only unambiguous cases where ss replaces eszett)
    WordPair("ausserdem", "außerdem"),
    WordPair("ausserhalb", "außerhalb"),
    WordPair("ausserordentlich", "außerordentlich"),
    WordPair("draussen", "draußen"),
    WordPair("fussball", "Fußball"),
    WordPair("gemaess", "gemäß"),
    WordPair("gemass", "gemäß"),
    WordPair("gruss", "Gruß"),
    WordPair("gruesse", "Grüße"),
    WordPair("heisst", "heißt"),
    WordPair("schliessen", "schließen"),
    WordPair("schliesst", "schließt"),
    WordPair("schliesslich", "schließlich"),
    WordPair("strasse", "Straße"),
    WordPair("strassen", "Straßen"),
)

_DE_WHITELIST: frozenset[str] = frozenset(
    {
        # English loan words that contain "ue", "ae", "oe"
        "queue",
        "queued",
        "queues",
        "queuing",
        "blue",
        "blues",
        "blueberry",
        "bluetooth",
        "clue",
        "clues",
        "continue",
        "continued",
        "continues",
        "continuing",
        "cue",
        "cued",
        "cues",
        "due",
        "duet",
        "fuel",
        "fueled",
        "fueling",
        "glue",
        "glued",
        "glues",
        "glueing",
        "sue",
        "sued",
        "sues",
        "suing",
        "issue",
        "issued",
        "issues",
        "issuing",
        "rescue",
        "rescued",
        "rescues",
        "residue",
        "revenue",
        "revenues",
        "statue",
        "statues",
        "tissue",
        "tissues",
        "tongue",
        "tongues",
        "true",
        "truer",
        "truest",
        "truly",
        "unique",
        "uniquely",
        "value",
        "valued",
        "values",
        "venue",
        "venues",
        "virtue",
        "virtues",
        # "ae" loan words
        "aerial",
        "aerobic",
        "aesthetics",
        "aesthetic",
        # "oe" loan words
        "does",
        "goes",
        "hoe",
        "hoes",
        "joe",
        "joey",
        "poet",
        "poetry",
        "poem",
        "poems",
        "shoe",
        "shoes",
        "toe",
        "toes",
        "toenail",
        "foe",
        "foes",
        "aloe",
        "canoe",
        "canoes",
        "oboe",
        "roe",
        # Technical terms and identifiers
        "user",
        "users",
        "user_id",
        "username",
        "usernames",
        "boolean",
        "booleans",
        "module",
        "modules",
        "router",
        "routers",
        "route",
        "routed",
        "routes",
        "routing",
        "request",
        "requests",
        "requested",
        "requesting",
        "response",
        "responses",
        "execute",
        "executed",
        "executes",
        "executing",
        "sequel",
        "parameter",
        "parameters",
        "procedure",
        "procedures",
        "scheduled",
        "scheduler",
        "schedulers",
        "structured",
        "unstructured",
        "feature",
        "features",
        "featured",
        "configure",
        "configured",
        "configures",
        "manufacture",
        "manufactured",
        "guest",
        "guests",
        "guess",
        "guessed",
        "guerrilla",
        "guarantee",
        "guaranteed",
        "guarantees",
        "catalogue",
        "dialogue",
        "monologue",
        "prologue",
        "technique",
        "techniques",
        "boutique",
        "antique",
        "antiques",
        "vogue",
    }
)

# ---------------------------------------------------------------------------
# French (fr)
# ---------------------------------------------------------------------------

_FR_WORD_PAIRS: tuple[WordPair, ...] = (
    # Missing accents on e
    WordPair("etre", "être"),
    WordPair("etait", "était"),
    WordPair("etaient", "étaient"),
    WordPair("ete", "été"),
    WordPair("etat", "état"),
    WordPair("etats", "états"),
    WordPair("etape", "étape"),
    WordPair("etapes", "étapes"),
    WordPair("evenement", "événement"),
    WordPair("evenements", "événements"),
    WordPair("ecole", "école"),
    WordPair("ecoles", "écoles"),
    WordPair("ecrire", "écrire"),
    WordPair("ecrit", "écrit"),
    WordPair("ecriture", "écriture"),
    WordPair("education", "éducation"),
    WordPair("egal", "égal"),
    WordPair("egalement", "également"),
    WordPair("eglise", "église"),
    WordPair("election", "élection"),
    WordPair("elections", "élections"),
    WordPair("eleve", "élève"),
    WordPair("eleves", "élèves"),
    WordPair("energie", "énergie"),
    WordPair("enorme", "énorme"),
    WordPair("enormement", "énormément"),
    WordPair("epoque", "époque"),
    WordPair("equipe", "équipe"),
    WordPair("equipes", "équipes"),
    WordPair("espece", "espèce"),
    WordPair("especes", "espèces"),
    WordPair("esperer", "espérer"),
    WordPair("etrange", "étrange"),
    WordPair("etranger", "étranger"),
    WordPair("etrangers", "étrangers"),
    WordPair("etude", "étude"),
    WordPair("etudes", "études"),
    WordPair("etudiant", "étudiant"),
    WordPair("etudiants", "étudiants"),
    WordPair("evidemment", "évidemment"),
    WordPair("evident", "évident"),
    WordPair("evoluer", "évoluer"),
    WordPair("evolution", "évolution"),
    # Accented a
    WordPair("deja", "déjà"),
    WordPair("voila", "voilà"),
    WordPair("a bientot", "à bientôt"),
    # Cedilla
    WordPair("francais", "français"),
    WordPair("francaise", "française"),
    WordPair("francaises", "françaises"),
    WordPair("garcon", "garçon"),
    WordPair("garcons", "garçons"),
    WordPair("lecon", "leçon"),
    WordPair("lecons", "leçons"),
    WordPair("recoit", "reçoit"),
    WordPair("recoivent", "reçoivent"),
    WordPair("facons", "façons"),
    WordPair("facon", "façon"),
    WordPair("decu", "déçu"),
    WordPair("decue", "déçue"),
    # Circumflex
    WordPair("bientot", "bientôt"),
    WordPair("cote", "côté"),
    WordPair("diplome", "diplôme"),
    WordPair("diplomes", "diplômes"),
    WordPair("hopital", "hôpital"),
    WordPair("hotel", "hôtel"),
    WordPair("hotels", "hôtels"),
    WordPair("ile", "île"),
    WordPair("iles", "îles"),
    WordPair("interet", "intérêt"),
    WordPair("interets", "intérêts"),
    WordPair("meme", "même"),
    WordPair("memes", "mêmes"),
    WordPair("role", "rôle"),
    WordPair("roles", "rôles"),
    WordPair("tot", "tôt"),
    # Trema
    WordPair("noel", "Noël"),
    WordPair("mais", "maïs"),
)

_FR_WHITELIST: frozenset[str] = frozenset(
    {
        # English words that look like unaccented French
        "age",
        "ages",
        "cage",
        "cages",
        "dose",
        "elite",
        "file",
        "files",
        "fine",
        "fines",
        "grave",
        "lame",
        "male",
        "males",
        "mere",
        "mole",
        "moles",
        "noble",
        "note",
        "notes",
        "page",
        "pages",
        "pale",
        "pile",
        "plane",
        "plate",
        "pole",
        "poles",
        "role",  # also correct in English without accent
        "roles",
        "rose",
        "roses",
        "route",
        "routes",
        "rule",
        "rules",
        "sale",
        "sales",
        "same",
        "scale",
        "sole",
        "stage",
        "stages",
        "table",
        "tables",
        "tale",
        "tales",
        "tube",
        "tubes",
        "zone",
        "zones",
        # Technical
        "module",
        "modules",
        "node",
        "nodes",
        "code",
        "codes",
        "mode",
        "modes",
        "state",
        "states",
    }
)

# ---------------------------------------------------------------------------
# Spanish (es)
# ---------------------------------------------------------------------------

_ES_WORD_PAIRS: tuple[WordPair, ...] = (
    # n instead of n-tilde
    WordPair("ano", "año"),
    WordPair("anos", "años"),
    WordPair("espanol", "español"),
    WordPair("espanola", "española"),
    WordPair("espanoles", "españoles"),
    WordPair("manana", "mañana"),
    WordPair("montana", "montaña"),
    WordPair("montanas", "montañas"),
    WordPair("nino", "niño"),
    WordPair("nina", "niña"),
    WordPair("ninos", "niños"),
    WordPair("ninas", "niñas"),
    WordPair("senor", "señor"),
    WordPair("senora", "señora"),
    WordPair("senores", "señores"),
    WordPair("sueno", "sueño"),
    WordPair("suenos", "sueños"),
    WordPair("pequeno", "pequeño"),
    WordPair("pequena", "pequeña"),
    WordPair("pequenos", "pequeños"),
    WordPair("pequenas", "pequeñas"),
    WordPair("companero", "compañero"),
    WordPair("companera", "compañera"),
    WordPair("companeros", "compañeros"),
    WordPair("companias", "compañías"),
    WordPair("compania", "compañía"),
    WordPair("ensenanza", "enseñanza"),
    WordPair("otono", "otoño"),
    WordPair("banera", "bañera"),
    WordPair("bano", "baño"),
    WordPair("banos", "baños"),
    WordPair("canon", "cañón"),
    WordPair("canones", "cañones"),
    WordPair("diseno", "diseño"),
    WordPair("disenos", "diseños"),
    WordPair("empeno", "empeño"),
    WordPair("enganar", "engañar"),
    WordPair("lena", "leña"),
    WordPair("pinata", "piñata"),
    WordPair("rinon", "riñón"),
    WordPair("vinedo", "viñedo"),
    # Missing accent marks on vowels
    WordPair("ademas", "además"),
    WordPair("aqui", "aquí"),
    WordPair("asi", "así"),
    WordPair("atras", "atrás"),
    WordPair("basico", "básico"),
    WordPair("basica", "básica"),
    WordPair("basicos", "básicos"),
    WordPair("basicas", "básicas"),
    WordPair("buscara", "buscará"),
    WordPair("cambiara", "cambiará"),
    WordPair("corazon", "corazón"),
    WordPair("despues", "después"),
    WordPair("detras", "detrás"),
    WordPair("dificil", "difícil"),
    WordPair("dificiles", "difíciles"),
    WordPair("direccion", "dirección"),
    WordPair("educacion", "educación"),
    WordPair("electronico", "electrónico"),
    WordPair("electronica", "electrónica"),
    WordPair("esta", "está"),
    WordPair("estan", "están"),
    WordPair("facil", "fácil"),
    WordPair("faciles", "fáciles"),
    WordPair("informacion", "información"),
    WordPair("jamas", "jamás"),
    WordPair("musica", "música"),
    WordPair("numero", "número"),
    WordPair("numeros", "números"),
    WordPair("pagina", "página"),
    WordPair("paginas", "páginas"),
    WordPair("pais", "país"),
    WordPair("paises", "países"),
    WordPair("razon", "razón"),
    WordPair("rapido", "rápido"),
    WordPair("rapida", "rápida"),
    WordPair("rapidos", "rápidos"),
    WordPair("rapidas", "rápidas"),
    WordPair("sera", "será"),
    WordPair("seran", "serán"),
    WordPair("situacion", "situación"),
    WordPair("solucion", "solución"),
    WordPair("tambien", "también"),
    WordPair("telefono", "teléfono"),
    WordPair("telefonos", "teléfonos"),
    WordPair("todavia", "todavía"),
    WordPair("ultima", "última"),
    WordPair("ultimo", "último"),
    WordPair("ultimos", "últimos"),
    WordPair("ultimas", "últimas"),
    WordPair("unico", "único"),
    WordPair("unica", "única"),
    WordPair("unicos", "únicos"),
    WordPair("unicas", "únicas"),
    WordPair("util", "útil"),
    WordPair("utiles", "útiles"),
)

_ES_WHITELIST: frozenset[str] = frozenset(
    {
        # English words that look like unaccented Spanish
        "also",
        "area",
        "areas",
        "auto",
        "basic",
        "data",
        "delta",
        "extra",
        "final",
        "formula",
        "general",
        "idea",
        "media",
        "metal",
        "mine",
        "minor",
        "monitor",
        "moral",
        "noble",
        "normal",
        "opera",
        "piano",
        "radio",
        "sofa",
        "solo",
        "studio",
        "super",
        "total",
        "triple",
        "tropical",
        "ultra",
        "via",
        "visa",
        "vista",
        "vital",
        "volume",
        "yoga",
    }
)

# ---------------------------------------------------------------------------
# Italian (it)
# ---------------------------------------------------------------------------

_IT_WORD_PAIRS: tuple[WordPair, ...] = (
    # Missing grave/acute accents on -ta (citta, qualita, etc.)
    WordPair("citta", "città"),
    WordPair("qualita", "qualità"),
    WordPair("realta", "realtà"),
    WordPair("societa", "società"),
    WordPair("universita", "università"),
    WordPair("verita", "verità"),
    WordPair("volonta", "volontà"),
    WordPair("liberta", "libertà"),
    WordPair("attivita", "attività"),
    WordPair("capacita", "capacità"),
    WordPair("comunita", "comunità"),
    WordPair("difficolta", "difficoltà"),
    WordPair("felicita", "felicità"),
    WordPair("identita", "identità"),
    WordPair("necessita", "necessità"),
    WordPair("novita", "novità"),
    WordPair("opportunita", "opportunità"),
    WordPair("possibilita", "possibilità"),
    WordPair("quantita", "quantità"),
    WordPair("responsabilita", "responsabilità"),
    WordPair("varieta", "varietà"),
    # e with accent (perche, nonche, etc.)
    WordPair("perche", "perché"),
    WordPair("poiche", "poiché"),
    WordPair("nonche", "nonché"),
    WordPair("affinche", "affinché"),
    WordPair("benche", "benché"),
    WordPair("finche", "finché"),
    WordPair("giacche", "giacché"),
    WordPair("cosicche", "cosicché"),
    # Common words with accents
    WordPair("gia", "già"),
    WordPair("piu", "più"),
    WordPair("cosi", "così"),
    WordPair("pero", "però"),
    WordPair("puo", "può"),
    WordPair("cioe", "cioè"),
    WordPair("eta", "età"),
)

_IT_WHITELIST: frozenset[str] = frozenset(
    {
        "area",
        "arena",
        "camera",
        "data",
        "era",
        "extra",
        "formula",
        "idea",
        "media",
        "meta",  # English "meta" is valid
        "opera",
        "piano",
        "pizza",
        "quota",
        "radio",
        "replica",
        "via",
        "visa",
        "vista",
        "villa",
        "yoga",
    }
)

# ---------------------------------------------------------------------------
# Portuguese (pt)
# ---------------------------------------------------------------------------

_PT_WORD_PAIRS: tuple[WordPair, ...] = (
    # Missing tilde on a/o
    WordPair("nao", "não"),
    WordPair("sao", "são"),
    WordPair("entao", "então"),
    WordPair("informacao", "informação"),
    WordPair("informacoes", "informações"),
    WordPair("situacao", "situação"),
    WordPair("situacoes", "situações"),
    WordPair("educacao", "educação"),
    WordPair("comunicacao", "comunicação"),
    WordPair("organizacao", "organização"),
    WordPair("populacao", "população"),
    WordPair("relacao", "relação"),
    WordPair("relacoes", "relações"),
    WordPair("solucao", "solução"),
    WordPair("solucoes", "soluções"),
    WordPair("coracoes", "corações"),
    WordPair("coracao", "coração"),
    WordPair("condicao", "condição"),
    WordPair("condicoes", "condições"),
    WordPair("irmao", "irmão"),
    WordPair("irmaos", "irmãos"),
    WordPair("mae", "mãe"),
    WordPair("maes", "mães"),
    WordPair("pao", "pão"),
    WordPair("paes", "pães"),
    # Missing cedilla
    WordPair("voce", "você"),
    WordPair("voces", "vocês"),
    WordPair("frances", "francês"),
    WordPair("funcao", "função"),
    WordPair("funcoes", "funções"),
    WordPair("licao", "lição"),
    WordPair("licoes", "lições"),
    WordPair("preco", "preço"),
    WordPair("precos", "preços"),
    WordPair("servico", "serviço"),
    WordPair("servicos", "serviços"),
    # Missing accent marks
    WordPair("agua", "água"),
    WordPair("aguas", "águas"),
    WordPair("alem", "além"),
    WordPair("ate", "até"),
    WordPair("dificil", "difícil"),
    WordPair("dificeis", "difíceis"),
    WordPair("facil", "fácil"),
    WordPair("faceis", "fáceis"),
    WordPair("familia", "família"),
    WordPair("familias", "famílias"),
    WordPair("historia", "história"),
    WordPair("historias", "histórias"),
    WordPair("impossivel", "impossível"),
    WordPair("ja", "já"),
    WordPair("musica", "música"),
    WordPair("musicas", "músicas"),
    WordPair("numero", "número"),
    WordPair("numeros", "números"),
    WordPair("pagina", "página"),
    WordPair("paginas", "páginas"),
    WordPair("pais", "país"),
    WordPair("paises", "países"),
    WordPair("possivel", "possível"),
    WordPair("rapido", "rápido"),
    WordPair("rapida", "rápida"),
    WordPair("saude", "saúde"),
    WordPair("tambem", "também"),
    WordPair("unico", "único"),
    WordPair("unica", "única"),
    WordPair("util", "útil"),
    WordPair("uteis", "úteis"),
)

_PT_WHITELIST: frozenset[str] = frozenset(
    {
        "area",
        "data",
        "extra",
        "final",
        "formula",
        "general",
        "idea",
        "media",
        "metal",
        "moral",
        "noble",
        "normal",
        "opera",
        "piano",
        "radio",
        "total",
        "ultra",
        "via",
        "visa",
        "vista",
        "yoga",
    }
)

# ---------------------------------------------------------------------------
# English (en): no-op rule set
# ---------------------------------------------------------------------------

_EN_WORD_PAIRS: tuple[WordPair, ...] = ()
_EN_WHITELIST: frozenset[str] = frozenset()

# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

_BUILTIN_RULES: dict[str, RuleSet] = {
    "de": RuleSet(
        language="de",
        word_pairs=_DE_WORD_PAIRS,
        loan_word_whitelist=_DE_WHITELIST,
    ),
    "fr": RuleSet(
        language="fr",
        word_pairs=_FR_WORD_PAIRS,
        loan_word_whitelist=_FR_WHITELIST,
    ),
    "es": RuleSet(
        language="es",
        word_pairs=_ES_WORD_PAIRS,
        loan_word_whitelist=_ES_WHITELIST,
    ),
    "it": RuleSet(
        language="it",
        word_pairs=_IT_WORD_PAIRS,
        loan_word_whitelist=_IT_WHITELIST,
    ),
    "pt": RuleSet(
        language="pt",
        word_pairs=_PT_WORD_PAIRS,
        loan_word_whitelist=_PT_WHITELIST,
    ),
    "en": RuleSet(
        language="en",
        word_pairs=_EN_WORD_PAIRS,
        loan_word_whitelist=_EN_WHITELIST,
    ),
}


def get_builtin_rules(language: str) -> RuleSet | None:
    """Get the built-in rule set for a language.

    Args:
        language: ISO 639-1 language code.

    Returns:
        RuleSet if available, None otherwise.
    """
    return _BUILTIN_RULES.get(language)


def list_languages() -> list[str]:
    """List all languages with built-in rule sets.

    Returns:
        Sorted list of ISO 639-1 language codes.
    """
    return sorted(_BUILTIN_RULES.keys())
